import {useEffect,useMemo,useState} from 'react';

type Cell={cell_id:string;canonical_name:string;tissue_origin?:string;diameter_um?:number;critical_shear_pa?:number;evidence_status:string;data_provenance?:Record<string,unknown>};
type Report={reynolds:number;velocity_m_s:number;pressure_drop_pa:number;wall_shear_pa:number;apparent_viscosity_pa_s:number;nozzle_shear_pa:number;nozzle_pressure_drop_pa:number;safety_factor:number;passed:boolean;issues:{field:string;severity:string;code:string;message:string}[]};
const API=import.meta.env.VITE_API_URL||'http://localhost:8000/api';
const defaults={cell_id:'',channel_width_um:1000,channel_height_um:200,channel_length_mm:20,wall_thickness_mm:1,build_width_mm:50,build_length_mm:50,flow_rate_ul_min:1,perfusion_viscosity_pa_s:.001,perfusion_density_kg_m3:1000,consistency_index_k:.001,flow_index_n:1,nozzle_diameter_um:410,nozzle_length_mm:1,extrusion_flow_rate_ul_min:1,pressure_kpa:50,print_speed_mm_s:10,temperature_c:25,cell_density_million_ml:1,fabrication_strategy:'cell_laden_bioprinting'};
export default function App(){
 const[cells,setCells]=useState<Cell[]>([]); const[cellId,setCellId]=useState(''); const[f,setF]=useState<any>(defaults); const[report,setReport]=useState<Report|null>(null); const[busy,setBusy]=useState(false); const[err,setErr]=useState('');
 useEffect(()=>{fetch(`${API}/cells`).then(r=>r.json()).then(d=>{const a=d.cells||[];setCells(a);if(a[0]){setCellId(a[0].cell_id);setF((x:any)=>({...x,cell_id:a[0].cell_id}))}}).catch(e=>setErr('API unavailable. Start the backend on port 8000.'))},[]);
 const selected=useMemo(()=>cells.find(c=>c.cell_id===cellId),[cells,cellId]);
 const update=(k:string,v:string)=>setF((x:any)=>({...x,[k]:k==='fabrication_strategy'?v:Number(v)}));
 async function validate(){setBusy(true);setErr('');try{const r=await fetch(`${API}/physics/validate`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...f,cell_id:cellId})});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Validation failed');setReport(d)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <div className="shell"><header><div><div className="eyebrow">SCIENTIFIC RESEARCH PLATFORM</div><h1>TissuePilot</h1><p>Evidence-aware tissue engineering, microfluidics & bioprinting design screening.</p></div><span className="badge">v1.8.0 · Scientific Hardened</span></header>
 <main><section className="card"><h2>Biological model</h2><label>Cell population<select value={cellId} onChange={e=>{setCellId(e.target.value);setF((x:any)=>({...x,cell_id:e.target.value}));setReport(null)}}>{cells.map(c=><option key={c.cell_id} value={c.cell_id}>{c.canonical_name}</option>)}</select></label>{selected&&<div className="evidence"><b>{selected.evidence_status}</b><span>{selected.tissue_origin||'Tissue origin not specified'}</span><span>{selected.diameter_um?`${selected.diameter_um} µm diameter`:'Diameter unavailable'}</span><span>{selected.critical_shear_pa?`${selected.critical_shear_pa} Pa candidate shear limit`:'Critical shear unavailable'}</span></div>}</section>
 <section className="grid"><div className="card"><h2>Perfusion</h2><Field l="Channel width (µm)" k="channel_width_um" f={f} u={update}/><Field l="Channel height (µm)" k="channel_height_um" f={f} u={update}/><Field l="Channel length (mm)" k="channel_length_mm" f={f} u={update}/><Field l="Perfusion flow (µL/min)" k="flow_rate_ul_min" f={f} u={update}/><Field l="Perfusate viscosity (Pa·s)" k="perfusion_viscosity_pa_s" f={f} u={update}/></div><div className="card"><h2>Extrusion</h2><Field l="Nozzle diameter (µm)" k="nozzle_diameter_um" f={f} u={update}/><Field l="Nozzle length (mm)" k="nozzle_length_mm" f={f} u={update}/><Field l="Extrusion flow (µL/min)" k="extrusion_flow_rate_ul_min" f={f} u={update}/><Field l="Consistency K (Pa·sⁿ)" k="consistency_index_k" f={f} u={update}/><Field l="Flow index n" k="flow_index_n" f={f} u={update}/></div></section>
 <section className="card controls"><div><h2>Scientific validation</h2><p>Deterministic screening only. Biological thresholds require approved primary evidence or verified laboratory data.</p></div><button onClick={validate} disabled={busy||!cellId}>{busy?'Calculating…':'Run validation'}</button></section>
 {err&&<div className="error">{err}</div>}{report&&<section className={`result ${report.passed?'pass':'fail'}`}><div><h2>{report.passed?'SCREENING PASS':'SCIENTIFIC REVIEW REQUIRED'}</h2><div className="metrics"><Metric n="Reynolds" v={report.reynolds.toPrecision(4)}/><Metric n="Wall shear" v={`${report.wall_shear_pa.toPrecision(4)} Pa`}/><Metric n="Nozzle shear" v={`${report.nozzle_shear_pa.toPrecision(4)} Pa`}/><Metric n="Pressure drop" v={`${report.pressure_drop_pa.toPrecision(4)} Pa`}/><Metric n="Safety factor" v={report.safety_factor.toPrecision(4)}/></div></div>{report.issues.length>0&&<div className="issues"><h3>Review items</h3>{report.issues.map((i,n)=><div key={n} className={i.severity}>{i.code}: {i.message}</div>)}</div>}</section>}
 <section className="note"><b>Scientific boundary:</b> TissuePilot does not infer a universal cell viability percentage from shear. Outputs require rheology characterization, experimental validation and source review before experimental use.</section></main></div>}
function Field({l,k,f,u}:{l:string;k:string;f:any;u:(k:string,v:string)=>void}){return <label>{l}<input type="number" value={f[k]} step="any" onChange={e=>u(k,e.target.value)}/></label>}
function Metric({n,v}:{n:string;v:string}){return <div><small>{n}</small><strong>{v}</strong></div>}
